# Generated by Django 4.2.7 on 2024-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80, unique=True, verbose_name='адрес')),
                ('latitude', models.FloatField(null=True, verbose_name='широта')),
                ('longitude', models.FloatField(null=True, verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'unique_together': {('address',)},
            },
        ),
    ]
