# Generated by Django 4.2.7 on 2023-11-23 10:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_makeorder_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='контактный телефон'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='контактный телефон'),
        ),
    ]
