# Generated by Django 4.2.7 on 2023-11-23 10:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_makeorder_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='контактный телефон'),
        ),
    ]
