# Generated by Django 4.2.7 on 2023-12-25 10:23

from django.db import migrations


def set_price_from_product(apps, schema_editor):

    ProductOrder = apps.get_model('foodcartapp', 'ProductOrder')

    for product_order in ProductOrder.objects.all().iterator():
        product_order.price = product_order.product.price
        product_order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_productorder_price_alter_productorder_order'),
    ]

    operations = [
        migrations.RunPython(set_price_from_product),
    ]
