# Generated by Django 4.2.7 on 2023-12-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_enter_price_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('У курьера', 'У курьера'), ('Готовится', 'Готовится'), ('Утвержденный', 'Утвержденный'), ('Необработанный', 'Необработанный')], db_index=True, default='Необработанный', max_length=20, verbose_name='статус'),
        ),
    ]
