# Generated by Django 4.2.7 on 2023-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_makeorder_registrate_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличные', 'Наличные'), ('Не указан', 'Не указан')], db_index=True, default='Не указан', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
