# Generated by Django 4.2.7 on 2023-12-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_makeorder_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='makeorder',
            options={'ordering': ['-status', 'id'], 'verbose_name': 'Оформление заказа', 'verbose_name_plural': 'Оформленные заказы'},
        ),
        migrations.AlterField(
            model_name='makeorder',
            name='status',
            field=models.CharField(choices=[('10', 'Завершен'), ('20', 'У курьера'), ('30', 'Готовится'), ('40', 'Утвержденный'), ('90', 'Необработанный')], db_index=True, default='90', max_length=20, verbose_name='статус'),
        ),
    ]
