# Generated by Django 4.2.7 on 2024-02-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_makeorder_options_alter_makeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='cook_restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Готовиться в'),
        ),
        migrations.AlterField(
            model_name='makeorder',
            name='status',
            field=models.CharField(choices=[('10', 'Завершен'), ('20', 'У курьера'), ('30', 'Готовится'), ('90', 'Необработанный')], db_index=True, default='90', max_length=20, verbose_name='статус'),
        ),
    ]
