# Generated by Django 4.2.7 on 2024-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='makeorder',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='makeorder',
            name='restaurant_distance',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True, verbose_name='растояние'),
        ),
    ]
