# Generated by Django 4.2.7 on 2024-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_remove_makeorder_restaurant_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='availability_geo',
            field=models.BooleanField(default=False, verbose_name='Доступность геоданных'),
        ),
    ]
