# Generated by Django 4.2.7 on 2024-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_makeorder_availability_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='availability_geo',
            field=models.BooleanField(default=True, verbose_name='Доступность координат'),
        ),
    ]
