# Generated by Django 4.2.7 on 2024-02-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_makeorder_availability_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeorder',
            name='availability_geo',
        ),
    ]
