# Generated by Django 4.2.7 on 2024-02-23 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_makeorder_availability_geo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakeOrder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='OrderItem',
        ),
    ]
