# Generated by Django 4.2.7 on 2024-02-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_remove_order_availability_geo_remove_order_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
    ]
